"""add token usage and model price tables

Revision ID: 001
Revises:
Create Date: 2025-04-12 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create feature_type enum
    feature_type_enum = sa.Enum(
        'CHAT', 'CHAT_STREAM', 'ASSET_GENERATION', 'ASSET_ORGANIZE',
        'TRADE_NEGOTIATION', 'TRADE_PRICING', 'INGEST_PIPELINE',
        'GRAPH_CONSTRUCTION', 'REVIEW', 'FILE_QUERY', 'EMBEDDING', 'OTHER',
        name='featuretype'
    )
    feature_type_enum.create(op.get_bind())

    # Create token_usages table
    op.create_table(
        'token_usages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.Enum('DEEPSEEK', 'OPENAI', 'QWEN', 'CUSTOM', name='llmprovider'), nullable=False),
        sa.Column('model', sa.String(length=100), nullable=False),
        sa.Column('is_custom_api', sa.Boolean(), default=False),
        sa.Column('feature_type', feature_type_enum, nullable=False),
        sa.Column('feature_detail', sa.String(length=200), nullable=True),
        sa.Column('prompt_tokens', sa.Integer(), default=0),
        sa.Column('completion_tokens', sa.Integer(), default=0),
        sa.Column('total_tokens', sa.Integer(), default=0),
        sa.Column('prompt_cost', sa.Float(), default=0.0),
        sa.Column('completion_cost', sa.Float(), default=0.0),
        sa.Column('total_cost', sa.Float(), default=0.0),
        sa.Column('request_id', sa.String(length=100), nullable=True),
        sa.Column('session_id', sa.String(length=100), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), default='success'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(), default=dict),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for token_usages
    op.create_index('idx_token_usage_user', 'token_usages', ['user_id'])
    op.create_index('idx_token_usage_feature', 'token_usages', ['feature_type'])
    op.create_index('idx_token_usage_model', 'token_usages', ['model'])
    op.create_index('idx_token_usage_created', 'token_usages', ['created_at'])
    op.create_index('idx_token_usage_user_created', 'token_usages', ['user_id', 'created_at'])
    op.create_index('idx_token_usage_request_id', 'token_usages', ['request_id'])
    op.create_index('idx_token_usage_session_id', 'token_usages', ['session_id'])

    # Create model_prices table
    op.create_table(
        'model_prices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('provider', sa.Enum('DEEPSEEK', 'OPENAI', 'QWEN', 'CUSTOM', name='llmprovider'), nullable=False),
        sa.Column('model', sa.String(length=100), nullable=False),
        sa.Column('prompt_price_per_1k', sa.Float(), nullable=False),
        sa.Column('completion_price_per_1k', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=10), default='USD'),
        sa.Column('effective_from', sa.DateTime(), nullable=True),
        sa.Column('effective_to', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider', 'model', name='uk_model_price')
    )

    # Create indexes for model_prices
    op.create_index('idx_model_price_provider', 'model_prices', ['provider'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('idx_model_price_provider', table_name='model_prices')
    op.drop_index('idx_token_usage_session_id', table_name='token_usages')
    op.drop_index('idx_token_usage_request_id', table_name='token_usages')
    op.drop_index('idx_token_usage_user_created', table_name='token_usages')
    op.drop_index('idx_token_usage_created', table_name='token_usages')
    op.drop_index('idx_token_usage_model', table_name='token_usages')
    op.drop_index('idx_token_usage_feature', table_name='token_usages')
    op.drop_index('idx_token_usage_user', table_name='token_usages')

    # Drop tables
    op.drop_table('model_prices')
    op.drop_table('token_usages')

    # Drop enums
    sa.Enum(name='featuretype').drop(op.get_bind())

    # ### end Alembic commands ###
