"""add escrow models

Revision ID: 002
Revises: 001
Create Date: 2025-04-12 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create escrow_status enum
    escrow_status_enum = sa.Enum(
        'LOCKED', 'RELEASED', 'REFUNDED', 'DISPUTED', 'EXPIRED',
        name='escrowstatus'
    )
    escrow_status_enum.create(op.get_bind())

    # Create escrow_records table
    op.create_table(
        'escrow_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('escrow_id', sa.String(32), unique=True, nullable=False),
        sa.Column('negotiation_id', sa.String(64), sa.ForeignKey('negotiation_sessions.negotiation_id'), nullable=False),
        sa.Column('listing_id', sa.String(32), nullable=False),
        sa.Column('buyer_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('seller_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('amount_cents', sa.BigInteger(), nullable=False),
        sa.Column('platform_fee_cents', sa.BigInteger(), default=0),
        sa.Column('seller_income_cents', sa.BigInteger(), default=0),
        sa.Column('status', escrow_status_enum, default='LOCKED', nullable=False),
        sa.Column('locked_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('released_at', sa.DateTime(), nullable=True),
        sa.Column('refunded_at', sa.DateTime(), nullable=True),
        sa.Column('released_by', sa.String(20), nullable=True),
        sa.Column('refund_reason', sa.Text(), nullable=True),
        sa.Column('version', sa.Integer(), default=1, nullable=False),
        sa.Column('metadata_json', postgresql.JSONB(), default=dict),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for escrow_records
    op.create_index('idx_escrow_negotiation', 'escrow_records', ['negotiation_id'])
    op.create_index('idx_escrow_buyer', 'escrow_records', ['buyer_id'])
    op.create_index('idx_escrow_seller', 'escrow_records', ['seller_id'])
    op.create_index('idx_escrow_status', 'escrow_records', ['status'])
    op.create_index('idx_escrow_expires', 'escrow_records', ['expires_at'])

    # Create escrow_transaction_logs table
    op.create_table(
        'escrow_transaction_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('log_id', sa.String(32), unique=True, nullable=False),
        sa.Column('escrow_id', sa.String(32), sa.ForeignKey('escrow_records.escrow_id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('transaction_type', sa.String(20), nullable=False),
        sa.Column('amount_cents', sa.BigInteger(), nullable=False),
        sa.Column('wallet_balance_before_cents', sa.BigInteger(), nullable=False),
        sa.Column('wallet_balance_after_cents', sa.BigInteger(), nullable=False),
        sa.Column('escrow_balance_before_cents', sa.BigInteger(), nullable=False),
        sa.Column('escrow_balance_after_cents', sa.BigInteger(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('metadata_json', postgresql.JSONB(), default=dict),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for escrow_transaction_logs
    op.create_index('idx_escrow_log_escrow', 'escrow_transaction_logs', ['escrow_id'])
    op.create_index('idx_escrow_log_user', 'escrow_transaction_logs', ['user_id'])
    op.create_index('idx_escrow_log_type', 'escrow_transaction_logs', ['transaction_type'])
    op.create_index('idx_escrow_log_created', 'escrow_transaction_logs', ['created_at'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('idx_escrow_log_created', table_name='escrow_transaction_logs')
    op.drop_index('idx_escrow_log_type', table_name='escrow_transaction_logs')
    op.drop_index('idx_escrow_log_user', table_name='escrow_transaction_logs')
    op.drop_index('idx_escrow_log_escrow', table_name='escrow_transaction_logs')

    op.drop_index('idx_escrow_expires', table_name='escrow_records')
    op.drop_index('idx_escrow_status', table_name='escrow_records')
    op.drop_index('idx_escrow_seller', table_name='escrow_records')
    op.drop_index('idx_escrow_buyer', table_name='escrow_records')
    op.drop_index('idx_escrow_negotiation', table_name='escrow_records')

    # Drop tables
    op.drop_table('escrow_transaction_logs')
    op.drop_table('escrow_records')

    # Drop enums
    sa.Enum(name='escrowstatus').drop(op.get_bind())

    # ### end Alembic commands ###
