"""fix wallet default balance

Revision ID: 003
Revises: 002
Create Date: 2025-04-13 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Update trade_wallets table: change liquid_credits default from 100000 to 0
    op.execute("""
        ALTER TABLE trade_wallets
        ALTER COLUMN liquid_credits
        SET DEFAULT 0
    """)

    # Note: We don't update existing records to avoid disrupting current users
    # Only new wallets will have the new default

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert to old default (100000 = 1000.00 credits)
    op.execute("""
        ALTER TABLE trade_wallets
        ALTER COLUMN liquid_credits
        SET DEFAULT 100000
    """)

    # ### end Alembic commands ###
