"""create negotiation_sessions table and add escrow_id

Revision ID: 004
Revises: 003
Create Date: 2025-04-13 13:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create mechanism_type enum (if not exists)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mechanismtype') THEN
                CREATE TYPE mechanismtype AS ENUM ('bilateral', 'auction', 'contract_net');
            END IF;
        END$$;
    """)

    # Create negotiation_status enum (if not exists)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'negotiationstatus') THEN
                CREATE TYPE negotiationstatus AS ENUM ('pending', 'active', 'accepted', 'rejected', 'cancelled', 'expired');
            END IF;
        END$$;
    """)

    # Check if table exists before creating
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                          WHERE table_schema = 'public'
                          AND table_name = 'negotiation_sessions') THEN
                CREATE TABLE negotiation_sessions (
                    id BIGSERIAL PRIMARY KEY,
                    negotiation_id VARCHAR(32) UNIQUE NOT NULL,
                    seller_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    buyer_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                    listing_id VARCHAR(32),
                    asset_id VARCHAR(32),
                    mechanism_type mechanismtype NOT NULL,
                    max_rounds INTEGER DEFAULT 10,
                    status negotiationstatus DEFAULT 'pending',
                    current_round INTEGER DEFAULT 0,
                    current_turn VARCHAR(16) DEFAULT 'seller',
                    starting_price BIGINT,
                    reserve_price BIGINT,
                    current_price BIGINT,
                    agreed_price BIGINT,
                    seller_floor_price BIGINT,
                    buyer_ceiling_price BIGINT,
                    seller_target_price BIGINT,
                    buyer_target_price BIGINT,
                    winner_user_id BIGINT REFERENCES users(id),
                    shared_board JSONB DEFAULT '{}',
                    settlement_result JSONB,
                    settlement_at TIMESTAMPTZ,
                    expires_at TIMESTAMPTZ,
                    last_activity_at TIMESTAMPTZ DEFAULT NOW(),
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW(),
                    escrow_id VARCHAR(32)
                );

                CREATE INDEX idx_negotiation_status ON negotiation_sessions(status);
                CREATE INDEX idx_negotiation_seller ON negotiation_sessions(seller_user_id);
                CREATE INDEX idx_negotiation_listing ON negotiation_sessions(listing_id);
                CREATE INDEX idx_negotiation_mechanism ON negotiation_sessions(mechanism_type);
                CREATE INDEX idx_negotiation_created ON negotiation_sessions(created_at);
                CREATE INDEX idx_negotiation_escrow ON negotiation_sessions(escrow_id);
            ELSE
                -- Table exists, just add escrow_id column
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                              WHERE table_schema = 'public'
                              AND table_name = 'negotiation_sessions'
                              AND column_name = 'escrow_id') THEN
                    ALTER TABLE negotiation_sessions ADD COLUMN escrow_id VARCHAR(32);
                    CREATE INDEX idx_negotiation_escrow ON negotiation_sessions(escrow_id);
                END IF;
            END IF;
        END$$;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop table
    op.execute("DROP TABLE IF EXISTS negotiation_sessions")

    # Drop enums
    op.execute("DROP TYPE IF EXISTS mechanismtype")
    op.execute("DROP TYPE IF EXISTS negotiationstatus")

    # ### end Alembic commands ###
