"""add escrow_id to negotiation_sessions

Revision ID: 004
Revises: 003
Create Date: 2025-04-13 13:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add escrow_id column to negotiation_sessions
    op.add_column(
        'negotiation_sessions',
        sa.Column(
            'escrow_id',
            sa.String(32),
            sa.ForeignKey('escrow_records.escrow_id'),
            nullable=True
        )
    )

    # Create index for efficient lookup
    op.create_index(
        'idx_negotiation_escrow',
        'negotiation_sessions',
        ['escrow_id'],
        unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index
    op.drop_index('idx_negotiation_escrow', table_name='negotiation_sessions')

    # Drop column
    op.drop_column('negotiation_sessions', 'escrow_id')

    # ### end Alembic commands ###
