"""add_missing_tables

Revision ID: b058866f8c43
Revises: 20260415_2122
Create Date: 2026-04-17 13:40:09.576186+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b058866f8c43'
down_revision: Union[str, None] = '20260415_2122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 清理所有残留的旧 ENUM 类型（数据库当前为空，安全删除）
    existing_enums = [
        'agent_task_status', 'blackboard_event_type', 'computationmethod',
        'datarightsstatus', 'datasensitivitylevel', 'document_status',
        'file_status', 'identity_type', 'ingest_status', 'listing_status',
        'mechanism_type', 'mechanismtype', 'message_status', 'message_type',
        'negotiation_status', 'negotiationstatus', 'order_status',
        'review_status', 'upload_status', 'yield_strategy',
    ]
    for enum_name in existing_enums:
        op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE")
    op.create_table('agent_decision_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('result_status', sa.String(length=16), nullable=True),
    sa.Column('result_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id')
    )
    op.create_index('idx_decision_agent', 'agent_decision_logs', ['agent_type'], unique=False)
    op.create_index('idx_decision_task', 'agent_decision_logs', ['task_id'], unique=False)
    op.create_index('idx_decision_time', 'agent_decision_logs', ['created_at'], unique=False)
    op.create_table('agent_intermediate_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(length=32), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('record_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    op.create_index('idx_intermediate_expires', 'agent_intermediate_results', ['expires_at'], unique=False)
    op.create_index('idx_intermediate_step', 'agent_intermediate_results', ['task_id', 'step_name'], unique=False)
    op.create_index('idx_intermediate_task', 'agent_intermediate_results', ['task_id'], unique=False)
    op.create_table('agent_rate_limits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('limit_type', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('is_throttled', sa.Boolean(), nullable=False),
    sa.Column('throttle_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limit_agent', 'agent_rate_limits', ['agent_id', 'window_start'], unique=False)
    op.create_index(op.f('ix_agent_rate_limits_agent_id'), 'agent_rate_limits', ['agent_id'], unique=False)
    op.create_table('asset_provenance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provenance_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('origin_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_name', sa.String(length=255), nullable=True),
    sa.Column('license_type', sa.String(length=64), nullable=True),
    sa.Column('verification_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_method', sa.String(length=32), nullable=True),
    sa.Column('record_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provenance_id')
    )
    op.create_index('idx_prov_asset', 'asset_provenance', ['asset_id'], unique=False)
    op.create_index('idx_prov_source', 'asset_provenance', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_asset_provenance_asset_id'), 'asset_provenance', ['asset_id'], unique=False)
    op.create_table('blackboard_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('BID', 'OFFER', 'COUNTER', 'ACCEPT', 'REJECT', 'WITHDRAW', 'CEILING_SET', 'FLOOR_SET', 'AGREEMENT', 'TIMEOUT', name='blackboard_event_type'), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_role', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vector_clock', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graph_node_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_blackboard_agent', 'blackboard_events', ['agent_id', 'event_timestamp'], unique=False)
    op.create_index('idx_blackboard_session_seq', 'blackboard_events', ['session_id', 'sequence_number'], unique=False)
    op.create_index('idx_blackboard_session_time', 'blackboard_events', ['session_id', 'event_timestamp'], unique=False)
    op.create_index('idx_blackboard_type', 'blackboard_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_blackboard_events_session_id'), 'blackboard_events', ['session_id'], unique=False)
    op.create_table('blackboard_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_session', 'blackboard_snapshots', ['session_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_blackboard_snapshots_session_id'), 'blackboard_snapshots', ['session_id'], unique=False)
    op.create_table('escrow_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('escrow_id', sa.String(length=32), nullable=False),
    sa.Column('negotiation_id', sa.String(length=64), nullable=False),
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_cents', sa.BigInteger(), nullable=True),
    sa.Column('seller_income_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('LOCKED', 'RELEASED', 'REFUNDED', 'DISPUTED', 'EXPIRED', name='escrowstatus'), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('released_by', sa.String(length=20), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiation_sessions.negotiation_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escrow_id')
    )
    op.create_index('idx_escrow_buyer', 'escrow_records', ['buyer_id'], unique=False)
    op.create_index('idx_escrow_expires', 'escrow_records', ['expires_at'], unique=False)
    op.create_index('idx_escrow_negotiation', 'escrow_records', ['negotiation_id'], unique=False)
    op.create_index('idx_escrow_seller', 'escrow_records', ['seller_id'], unique=False)
    op.create_index('idx_escrow_status', 'escrow_records', ['status'], unique=False)
    op.create_table('model_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('DEEPSEEK', 'OPENAI', 'QWEN', 'CUSTOM', name='llmprovider'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_price_per_1k', sa.Float(), nullable=False),
    sa.Column('completion_price_per_1k', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model', name='uk_model_price')
    )
    op.create_index('idx_model_price_provider', 'model_prices', ['provider'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('processor_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_outbox_aggregate', 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('idx_outbox_status_created', 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_table('agent_message_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('negotiation_id', sa.String(length=32), nullable=False),
    sa.Column('from_agent_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_agent_user_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_type', sa.Enum('ANNOUNCE', 'BID', 'OFFER', 'COUNTER', 'ACCEPT', 'REJECT', 'QUERY', 'RESPONSE', 'COMMIT', 'SETTLE', name='message_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'processed', 'failed', name='message_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiation_sessions.negotiation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_agent_msg_created', 'agent_message_queue', ['created_at'], unique=False)
    op.create_index('idx_agent_msg_negotiation', 'agent_message_queue', ['negotiation_id'], unique=False)
    op.create_index('idx_agent_msg_priority', 'agent_message_queue', ['priority', 'created_at'], unique=False)
    op.create_index('idx_agent_msg_status', 'agent_message_queue', ['status'], unique=False)
    op.create_index('idx_agent_msg_to', 'agent_message_queue', ['to_agent_user_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('space_id', sa.String(length=32), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_conv_session_last_msg', 'conversation_sessions', ['user_id', 'last_message_at'], unique=False)
    op.create_index('idx_conv_session_space', 'conversation_sessions', ['space_id'], unique=False)
    op.create_index('idx_conv_session_status', 'conversation_sessions', ['status'], unique=False)
    op.create_index('idx_conv_session_user', 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('data_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=False),
    sa.Column('asset_description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('sensitivity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='datasensitivitylevel'), nullable=False),
    sa.Column('default_anonymization_level', sa.Integer(), nullable=True),
    sa.Column('quality_completeness', sa.Float(), nullable=True),
    sa.Column('quality_accuracy', sa.Float(), nullable=True),
    sa.Column('quality_timeliness', sa.Float(), nullable=True),
    sa.Column('quality_consistency', sa.Float(), nullable=True),
    sa.Column('quality_uniqueness', sa.Float(), nullable=True),
    sa.Column('quality_overall_score', sa.Float(), nullable=True),
    sa.Column('raw_data_source', sa.String(length=500), nullable=False),
    sa.Column('lineage_root', sa.String(length=64), nullable=True),
    sa.Column('processing_chain_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_location', sa.String(length=500), nullable=False),
    sa.Column('data_size_bytes', sa.Integer(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('related_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_available_for_trade', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('space_public_id', sa.String(length=32), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=True),
    sa.Column('asset_origin', sa.String(length=32), nullable=True),
    sa.Column('asset_status', sa.String(length=32), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_summary', sa.String(length=500), nullable=True),
    sa.Column('graph_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_assets_asset_id'), 'data_assets', ['asset_id'], unique=True)
    op.create_index('ix_data_assets_owner', 'data_assets', ['owner_id'], unique=False)
    op.create_index('ix_data_assets_quality', 'data_assets', ['quality_overall_score'], unique=False)
    op.create_index('ix_data_assets_sensitivity', 'data_assets', ['sensitivity_level'], unique=False)
    op.create_index('ix_data_assets_space', 'data_assets', ['space_public_id'], unique=False)
    op.create_index('ix_data_assets_type', 'data_assets', ['data_type'], unique=False)
    op.create_table('data_lineage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lineage_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('transformations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('current_entity_type', sa.String(length=32), nullable=False),
    sa.Column('current_entity_id', sa.String(length=32), nullable=False),
    sa.Column('parent_lineage_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_lineage_id'], ['data_lineage.lineage_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineage_id')
    )
    op.create_index('idx_lineage_current', 'data_lineage', ['current_entity_type', 'current_entity_id'], unique=False)
    op.create_index('idx_lineage_parent', 'data_lineage', ['parent_lineage_id'], unique=False)
    op.create_index('idx_lineage_source', 'data_lineage', ['source_type', 'source_id'], unique=False)
    op.create_table('escrow_transaction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.String(length=32), nullable=False),
    sa.Column('escrow_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('wallet_balance_before_cents', sa.BigInteger(), nullable=False),
    sa.Column('wallet_balance_after_cents', sa.BigInteger(), nullable=False),
    sa.Column('escrow_balance_before_cents', sa.BigInteger(), nullable=False),
    sa.Column('escrow_balance_after_cents', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_records.escrow_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id')
    )
    op.create_index('idx_escrow_log_created', 'escrow_transaction_logs', ['created_at'], unique=False)
    op.create_index('idx_escrow_log_escrow', 'escrow_transaction_logs', ['escrow_id'], unique=False)
    op.create_index('idx_escrow_log_type', 'escrow_transaction_logs', ['transaction_type'], unique=False)
    op.create_index('idx_escrow_log_user', 'escrow_transaction_logs', ['user_id'], unique=False)
    op.create_table('negotiation_history_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.String(length=32), nullable=False),
    sa.Column('negotiation_id', sa.String(length=32), nullable=False),
    sa.Column('layer', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('round_start', sa.Integer(), nullable=False),
    sa.Column('round_end', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('price_trajectory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_rounds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('concession_magnitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiation_sessions.negotiation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id')
    )
    op.create_index('idx_summary_layer', 'negotiation_history_summaries', ['negotiation_id', 'layer'], unique=False)
    op.create_index('idx_summary_negotiation', 'negotiation_history_summaries', ['negotiation_id'], unique=False)
    op.create_index('idx_summary_round_range', 'negotiation_history_summaries', ['negotiation_id', 'round_start', 'round_end'], unique=False)
    op.create_table('resource_acl',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('acl_id', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.String(length=32), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_write', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_share', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_execute', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inherit_from', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acl_id')
    )
    op.create_index('idx_acl_inherit', 'resource_acl', ['inherit_from'], unique=False)
    op.create_index('idx_acl_resource', 'resource_acl', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_acl_user', 'resource_acl', ['user_id'], unique=False)
    op.create_table('token_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('DEEPSEEK', 'OPENAI', 'QWEN', 'CUSTOM', name='llmprovider'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_custom_api', sa.Boolean(), nullable=True),
    sa.Column('feature_type', sa.Enum('CHAT', 'CHAT_STREAM', 'ASSET_GENERATION', 'ASSET_ORGANIZE', 'TRADE_NEGOTIATION', 'TRADE_PRICING', 'INGEST_PIPELINE', 'GRAPH_CONSTRUCTION', 'REVIEW', 'FILE_QUERY', 'EMBEDDING', 'OTHER', name='featuretype'), nullable=False),
    sa.Column('feature_detail', sa.String(length=200), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_cost', sa.Float(), nullable=True),
    sa.Column('completion_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_created', 'token_usages', ['created_at'], unique=False)
    op.create_index('idx_token_usage_feature', 'token_usages', ['feature_type'], unique=False)
    op.create_index('idx_token_usage_model', 'token_usages', ['model'], unique=False)
    op.create_index('idx_token_usage_user', 'token_usages', ['user_id'], unique=False)
    op.create_index('idx_token_usage_user_created', 'token_usages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usages_request_id'), 'token_usages', ['request_id'], unique=False)
    op.create_index(op.f('ix_token_usages_session_id'), 'token_usages', ['session_id'], unique=False)
    op.create_table('user_agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('DEEPSEEK', 'OPENAI', 'QWEN', 'CUSTOM', name='llmprovider'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('trade_auto_negotiate', sa.Boolean(), nullable=True),
    sa.Column('trade_max_rounds', sa.Integer(), nullable=True),
    sa.Column('trade_min_profit_margin', sa.Float(), nullable=True),
    sa.Column('trade_max_budget_ratio', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uk_user_agent_config')
    )
    op.create_index('idx_agent_config_user', 'user_agent_configs', ['user_id'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'conversation'"), nullable=False),
    sa.Column('source_session_id', sa.String(length=32), nullable=True),
    sa.Column('importance', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('access_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id')
    )
    op.create_index('idx_memory_source', 'user_memories', ['source'], unique=False)
    op.create_index('idx_memory_user', 'user_memories', ['user_id'], unique=False)
    op.create_index('idx_memory_user_type', 'user_memories', ['user_id', 'memory_type'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pref_type', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'implicit'"), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pref_type', 'key', name='uk_user_pref')
    )
    op.create_index('idx_pref_type', 'user_preferences', ['pref_type'], unique=False)
    op.create_index('idx_pref_user', 'user_preferences', ['user_id'], unique=False)
    op.create_table('collaboration_operations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(length=32), nullable=False),
    sa.Column('space_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operation_summary', sa.String(length=255), nullable=True),
    sa.Column('vector_clock', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_to_clients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index('idx_collab_entity', 'collaboration_operations', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_collab_space', 'collaboration_operations', ['space_id'], unique=False)
    op.create_index('idx_collab_time', 'collaboration_operations', ['operation_timestamp'], unique=False)
    op.create_index('idx_collab_user', 'collaboration_operations', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('record_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_msg_agent_type', 'conversation_messages', ['agent_type'], unique=False)
    op.create_index('idx_msg_session_time', 'conversation_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_msg_user', 'conversation_messages', ['user_id'], unique=False)
    op.create_table('data_lineage_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('parent_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_logic_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['data_assets.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_lineage_nodes_node_id'), 'data_lineage_nodes', ['node_id'], unique=True)
    op.create_index('ix_lineage_asset', 'data_lineage_nodes', ['asset_id'], unique=False)
    op.create_index('ix_lineage_type', 'data_lineage_nodes', ['node_type'], unique=False)
    op.create_table('data_rights_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('negotiation_id', sa.String(length=64), nullable=True),
    sa.Column('listing_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('data_asset_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('rights_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computation_method', sa.Enum('FEDERATED_LEARNING', 'MULTI_PARTY_COMPUTATION', 'TEE', 'DIFFERENTIAL_PRIVACY', 'RAW_DATA', name='computationmethod'), nullable=False),
    sa.Column('anonymization_level', sa.Integer(), nullable=False),
    sa.Column('computation_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('agreed_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'GRANTED', 'EXPIRED', 'REVOKED', 'VIOLATED', name='datarightsstatus'), nullable=True),
    sa.Column('settlement_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('settlement_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_asset_id'], ['data_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiation_sessions.negotiation_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_rights_transactions_listing_id'), 'data_rights_transactions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_data_rights_transactions_order_id'), 'data_rights_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_data_rights_transactions_transaction_id'), 'data_rights_transactions', ['transaction_id'], unique=True)
    op.create_index('ix_rights_tx_asset', 'data_rights_transactions', ['data_asset_id'], unique=False)
    op.create_index('ix_rights_tx_buyer', 'data_rights_transactions', ['buyer_id'], unique=False)
    op.create_index('ix_rights_tx_owner', 'data_rights_transactions', ['owner_id'], unique=False)
    op.create_index('ix_rights_tx_status', 'data_rights_transactions', ['status'], unique=False)
    op.create_index('ix_rights_tx_validity', 'data_rights_transactions', ['valid_from', 'valid_until'], unique=False)
    op.create_table('space_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('space_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'viewer'"), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('invite_status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'user_id', name='uk_space_member')
    )
    op.create_index('idx_space_member_role', 'space_members', ['space_id', 'role'], unique=False)
    op.create_index('idx_space_member_user', 'space_members', ['user_id'], unique=False)
    op.create_table('data_access_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('negotiation_id', sa.String(length=64), nullable=True),
    sa.Column('data_asset_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('access_timestamp', sa.DateTime(), nullable=True),
    sa.Column('access_purpose', sa.String(length=200), nullable=False),
    sa.Column('computation_method_used', sa.Enum('FEDERATED_LEARNING', 'MULTI_PARTY_COMPUTATION', 'TEE', 'DIFFERENTIAL_PRIVACY', 'RAW_DATA', name='computationmethod'), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('query_complexity_score', sa.Float(), nullable=True),
    sa.Column('result_size_bytes', sa.Integer(), nullable=True),
    sa.Column('result_row_count', sa.Integer(), nullable=True),
    sa.Column('result_aggregation_level', sa.String(length=50), nullable=False),
    sa.Column('policy_compliance_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('anomaly_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['data_rights_transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_buyer', 'data_access_audit_logs', ['buyer_id'], unique=False)
    op.create_index('ix_audit_risk', 'data_access_audit_logs', ['risk_score'], unique=False)
    op.create_index('ix_audit_timestamp', 'data_access_audit_logs', ['access_timestamp'], unique=False)
    op.create_index('ix_audit_tx', 'data_access_audit_logs', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_data_access_audit_logs_log_id'), 'data_access_audit_logs', ['log_id'], unique=True)
    op.create_table('policy_violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('violation_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('negotiation_id', sa.String(length=64), nullable=True),
    sa.Column('data_asset_id', sa.String(length=64), nullable=False),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('violation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('potential_data_exposure', sa.Float(), nullable=True),
    sa.Column('affected_records_estimate', sa.Integer(), nullable=True),
    sa.Column('automatic_action_taken', sa.String(length=200), nullable=True),
    sa.Column('manual_review_status', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['data_rights_transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_violations_violation_id'), 'policy_violations', ['violation_id'], unique=True)
    op.create_index('ix_violation_severity', 'policy_violations', ['severity'], unique=False)
    op.create_index('ix_violation_status', 'policy_violations', ['manual_review_status'], unique=False)
    op.create_index('ix_violation_tx', 'policy_violations', ['transaction_id'], unique=False)
    op.create_index('ix_violation_type', 'policy_violations', ['violation_type'], unique=False)
    op.add_column('agent_tasks', sa.Column('negotiation_session_id', sa.String(length=32), nullable=True))
    op.add_column('agent_tasks', sa.Column('trade_goal_type', sa.String(length=32), nullable=True))
    op.add_column('agent_tasks', sa.Column('execution_plan_id', sa.String(length=32), nullable=True))
    op.add_column('agent_tasks', sa.Column('progress_percentage', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('agent_tasks', sa.Column('current_step', sa.String(length=64), nullable=True))
    op.alter_column('doc_chunk_embeddings', 'embedding',
               existing_type=Vector(dim=1536),
               nullable=False)
    op.alter_column('doc_chunk_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('doc_chunk_embeddings_chunk_id_model_key', 'doc_chunk_embeddings', type_='unique')
    op.create_index('idx_chunk_embeddings_chunk', 'doc_chunk_embeddings', ['chunk_id'], unique=False)
    op.create_unique_constraint('uk_chunk_model', 'doc_chunk_embeddings', ['chunk_id', 'model'])
    op.alter_column('doc_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('doc_chunks_doc_id_chunk_index_key', 'doc_chunks', type_='unique')
    op.create_index('idx_doc_chunks_doc', 'doc_chunks', ['doc_id'], unique=False)
    op.create_unique_constraint('uk_doc_chunks_doc_index', 'doc_chunks', ['doc_id', 'chunk_index'])
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='document_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::document_status"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_documents_file_version', 'documents', ['file_version_id'], unique=False)
    op.create_index('idx_documents_space', 'documents', ['space_id'], unique=False)
    op.create_unique_constraint('uk_documents_graph_id', 'documents', ['graph_id'])
    op.create_foreign_key(None, 'documents', 'file_versions', ['file_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'documents', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    op.alter_column('file_versions', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('file_versions', 'sha256',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_constraint('file_versions_file_id_version_no_key', 'file_versions', type_='unique')
    op.drop_constraint('file_versions_public_id_key', 'file_versions', type_='unique')
    op.create_index('fk_file_versions_file', 'file_versions', ['file_id'], unique=False)
    op.create_unique_constraint('uk_file_version_no', 'file_versions', ['file_id', 'version_no'])
    op.create_unique_constraint('uk_version_public_id', 'file_versions', ['public_id'])
    op.drop_constraint('file_versions_created_by_fkey', 'file_versions', type_='foreignkey')
    op.drop_constraint('file_versions_file_id_fkey', 'file_versions', type_='foreignkey')
    op.create_foreign_key('fk_file_versions_file', 'file_versions', 'files', ['file_id'], ['id'])
    op.alter_column('files', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('files', 'sha256',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_constraint('files_public_id_key', 'files', type_='unique')
    op.drop_index('idx_files_current_version', table_name='files')
    op.create_index('fk_files_current_version', 'files', ['current_version_id'], unique=False)
    op.create_unique_constraint('uk_file_public_id', 'files', ['public_id'])
    op.drop_constraint('files_space_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_created_by_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_folder_id_fkey', 'files', type_='foreignkey')
    op.alter_column('folders', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('folders_public_id_key', 'folders', type_='unique')
    op.drop_constraint('folders_space_id_parent_id_name_key', 'folders', type_='unique')
    op.create_unique_constraint('uk_folder_public_id', 'folders', ['public_id'])
    op.create_unique_constraint('uk_folder_sibling_name', 'folders', ['space_id', 'parent_id', 'name'])
    op.drop_constraint('folders_parent_id_fkey', 'folders', type_='foreignkey')
    op.drop_constraint('folders_created_by_fkey', 'folders', type_='foreignkey')
    op.drop_constraint('folders_space_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'ingest_jobs', 'documents', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.add_column('negotiation_sessions', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('negotiation_sessions', sa.Column('engine_type', sa.String(length=16), server_default=sa.text("'simple'"), nullable=False))
    op.add_column('negotiation_sessions', sa.Column('selection_reason', sa.Text(), nullable=True))
    op.add_column('negotiation_sessions', sa.Column('autonomy_mode', sa.String(length=16), server_default=sa.text("'notify'"), nullable=False))
    op.add_column('negotiation_sessions', sa.Column('approval_status', sa.String(length=16), nullable=True))
    op.add_column('negotiation_sessions', sa.Column('initiating_task_id', sa.String(length=32), nullable=True))
    op.add_column('negotiation_sessions', sa.Column('expected_participants', sa.Integer(), server_default=sa.text('2'), nullable=False))
    op.add_column('negotiation_sessions', sa.Column('requires_full_audit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('negotiation_sessions', sa.Column('last_projection_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('negotiation_sessions', 'mechanism_type',
               existing_type=postgresql.ENUM('bilateral', 'auction', 'contract_net', name='mechanismtype'),
               type_=sa.Enum('fixed_price', 'bilateral', 'auction', 'contract_net', 'blackboard', name='mechanism_type'),
               existing_nullable=False)
    op.alter_column('negotiation_sessions', 'max_rounds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('negotiation_sessions', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'accepted', 'rejected', 'cancelled', 'expired', name='negotiationstatus'),
               type_=sa.Enum('pending', 'active', 'paused', 'agreed', 'settled', 'cancelled', 'terminated', 'disputed', name='negotiation_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::negotiationstatus"))
    op.alter_column('negotiation_sessions', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('negotiation_sessions', 'current_turn',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'seller'::character varying"))
    op.alter_column('negotiation_sessions', 'shared_board',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('negotiation_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('negotiation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('negotiation_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_negotiation_escrow', table_name='negotiation_sessions')
    op.create_foreign_key(None, 'negotiation_sessions', 'escrow_records', ['escrow_id'], ['escrow_id'])
    op.create_foreign_key(None, 'review_logs', 'documents', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.alter_column('spaces', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('spaces_public_id_key', 'spaces', type_='unique')
    op.create_unique_constraint('uk_space_public_id', 'spaces', ['public_id'])
    op.create_foreign_key(None, 'trade_orders', 'trade_listings', ['listing_id'], ['public_id'])
    op.alter_column('uploads', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uploads_public_id_key', 'uploads', type_='unique')
    op.create_unique_constraint('uk_upload_public_id', 'uploads', ['public_id'])
    op.drop_constraint('uploads_created_by_fkey', 'uploads', type_='foreignkey')
    op.drop_constraint('uploads_folder_id_fkey', 'uploads', type_='foreignkey')
    op.drop_constraint('uploads_space_id_fkey', 'uploads', type_='foreignkey')
    op.alter_column('user_auth', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('user_auth_identity_type_identifier_key', 'user_auth', type_='unique')
    op.create_unique_constraint('uk_identity', 'user_auth', ['identity_type', 'identifier'])
    op.drop_constraint('user_auth_user_id_fkey', 'user_auth', type_='foreignkey')
    op.create_foreign_key('fk_auth_user', 'user_auth', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('users_user_key_key', 'users', type_='unique')
    op.create_unique_constraint('uk_user_key', 'users', ['user_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_user_key', 'users', type_='unique')
    op.create_unique_constraint('users_user_key_key', 'users', ['user_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('fk_auth_user', 'user_auth', type_='foreignkey')
    op.create_foreign_key('user_auth_user_id_fkey', 'user_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uk_identity', 'user_auth', type_='unique')
    op.create_unique_constraint('user_auth_identity_type_identifier_key', 'user_auth', ['identity_type', 'identifier'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_auth', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key('uploads_space_id_fkey', 'uploads', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('uploads_folder_id_fkey', 'uploads', 'folders', ['folder_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('uploads_created_by_fkey', 'uploads', 'users', ['created_by'], ['id'])
    op.drop_constraint('uk_upload_public_id', 'uploads', type_='unique')
    op.create_unique_constraint('uploads_public_id_key', 'uploads', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('uploads', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'trade_orders', type_='foreignkey')
    op.drop_constraint('uk_space_public_id', 'spaces', type_='unique')
    op.create_unique_constraint('spaces_public_id_key', 'spaces', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('spaces', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'review_logs', type_='foreignkey')
    op.drop_constraint(None, 'negotiation_sessions', type_='foreignkey')
    op.create_index('idx_negotiation_escrow', 'negotiation_sessions', ['escrow_id'], unique=False)
    op.alter_column('negotiation_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('negotiation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('negotiation_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('negotiation_sessions', 'shared_board',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('negotiation_sessions', 'current_turn',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'seller'::character varying"))
    op.alter_column('negotiation_sessions', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('negotiation_sessions', 'status',
               existing_type=sa.Enum('pending', 'active', 'paused', 'agreed', 'settled', 'cancelled', 'terminated', 'disputed', name='negotiation_status'),
               type_=postgresql.ENUM('pending', 'active', 'accepted', 'rejected', 'cancelled', 'expired', name='negotiationstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::negotiationstatus"))
    op.alter_column('negotiation_sessions', 'max_rounds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('negotiation_sessions', 'mechanism_type',
               existing_type=sa.Enum('fixed_price', 'bilateral', 'auction', 'contract_net', 'blackboard', name='mechanism_type'),
               type_=postgresql.ENUM('bilateral', 'auction', 'contract_net', name='mechanismtype'),
               existing_nullable=False)
    op.drop_column('negotiation_sessions', 'last_projection_version')
    op.drop_column('negotiation_sessions', 'requires_full_audit')
    op.drop_column('negotiation_sessions', 'expected_participants')
    op.drop_column('negotiation_sessions', 'initiating_task_id')
    op.drop_column('negotiation_sessions', 'approval_status')
    op.drop_column('negotiation_sessions', 'autonomy_mode')
    op.drop_column('negotiation_sessions', 'selection_reason')
    op.drop_column('negotiation_sessions', 'engine_type')
    op.drop_column('negotiation_sessions', 'version')
    op.drop_constraint(None, 'ingest_jobs', type_='foreignkey')
    op.create_foreign_key('folders_space_id_fkey', 'folders', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('folders_created_by_fkey', 'folders', 'users', ['created_by'], ['id'])
    op.create_foreign_key('folders_parent_id_fkey', 'folders', 'folders', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uk_folder_sibling_name', 'folders', type_='unique')
    op.drop_constraint('uk_folder_public_id', 'folders', type_='unique')
    op.create_unique_constraint('folders_space_id_parent_id_name_key', 'folders', ['space_id', 'parent_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('folders_public_id_key', 'folders', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('folders', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key('files_folder_id_fkey', 'files', 'folders', ['folder_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('files_created_by_fkey', 'files', 'users', ['created_by'], ['id'])
    op.create_foreign_key('files_space_id_fkey', 'files', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uk_file_public_id', 'files', type_='unique')
    op.drop_index('fk_files_current_version', table_name='files')
    op.create_index('idx_files_current_version', 'files', ['current_version_id'], unique=False)
    op.create_unique_constraint('files_public_id_key', 'files', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('files', 'sha256',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=True)
    op.alter_column('files', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('fk_file_versions_file', 'file_versions', type_='foreignkey')
    op.create_foreign_key('file_versions_file_id_fkey', 'file_versions', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('file_versions_created_by_fkey', 'file_versions', 'users', ['created_by'], ['id'])
    op.drop_constraint('uk_version_public_id', 'file_versions', type_='unique')
    op.drop_constraint('uk_file_version_no', 'file_versions', type_='unique')
    op.drop_index('fk_file_versions_file', table_name='file_versions')
    op.create_unique_constraint('file_versions_public_id_key', 'file_versions', ['public_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('file_versions_file_id_version_no_key', 'file_versions', ['file_id', 'version_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('file_versions', 'sha256',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=True)
    op.alter_column('file_versions', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint('uk_documents_graph_id', 'documents', type_='unique')
    op.drop_index('idx_documents_space', table_name='documents')
    op.drop_index('idx_documents_file_version', table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='document_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::document_status"))
    op.drop_constraint('uk_doc_chunks_doc_index', 'doc_chunks', type_='unique')
    op.drop_index('idx_doc_chunks_doc', table_name='doc_chunks')
    op.create_unique_constraint('doc_chunks_doc_id_chunk_index_key', 'doc_chunks', ['doc_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.alter_column('doc_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uk_chunk_model', 'doc_chunk_embeddings', type_='unique')
    op.drop_index('idx_chunk_embeddings_chunk', table_name='doc_chunk_embeddings')
    op.create_unique_constraint('doc_chunk_embeddings_chunk_id_model_key', 'doc_chunk_embeddings', ['chunk_id', 'model'], postgresql_nulls_not_distinct=False)
    op.alter_column('doc_chunk_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('doc_chunk_embeddings', 'embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    op.drop_column('agent_tasks', 'current_step')
    op.drop_column('agent_tasks', 'progress_percentage')
    op.drop_column('agent_tasks', 'execution_plan_id')
    op.drop_column('agent_tasks', 'trade_goal_type')
    op.drop_column('agent_tasks', 'negotiation_session_id')
    op.drop_index('ix_violation_type', table_name='policy_violations')
    op.drop_index('ix_violation_tx', table_name='policy_violations')
    op.drop_index('ix_violation_status', table_name='policy_violations')
    op.drop_index('ix_violation_severity', table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_violation_id'), table_name='policy_violations')
    op.drop_table('policy_violations')
    op.drop_index(op.f('ix_data_access_audit_logs_log_id'), table_name='data_access_audit_logs')
    op.drop_index('ix_audit_tx', table_name='data_access_audit_logs')
    op.drop_index('ix_audit_timestamp', table_name='data_access_audit_logs')
    op.drop_index('ix_audit_risk', table_name='data_access_audit_logs')
    op.drop_index('ix_audit_buyer', table_name='data_access_audit_logs')
    op.drop_table('data_access_audit_logs')
    op.drop_index('idx_space_member_user', table_name='space_members')
    op.drop_index('idx_space_member_role', table_name='space_members')
    op.drop_table('space_members')
    op.drop_index('ix_rights_tx_validity', table_name='data_rights_transactions')
    op.drop_index('ix_rights_tx_status', table_name='data_rights_transactions')
    op.drop_index('ix_rights_tx_owner', table_name='data_rights_transactions')
    op.drop_index('ix_rights_tx_buyer', table_name='data_rights_transactions')
    op.drop_index('ix_rights_tx_asset', table_name='data_rights_transactions')
    op.drop_index(op.f('ix_data_rights_transactions_transaction_id'), table_name='data_rights_transactions')
    op.drop_index(op.f('ix_data_rights_transactions_order_id'), table_name='data_rights_transactions')
    op.drop_index(op.f('ix_data_rights_transactions_listing_id'), table_name='data_rights_transactions')
    op.drop_table('data_rights_transactions')
    op.drop_index('ix_lineage_type', table_name='data_lineage_nodes')
    op.drop_index('ix_lineage_asset', table_name='data_lineage_nodes')
    op.drop_index(op.f('ix_data_lineage_nodes_node_id'), table_name='data_lineage_nodes')
    op.drop_table('data_lineage_nodes')
    op.drop_index('idx_msg_user', table_name='conversation_messages')
    op.drop_index('idx_msg_session_time', table_name='conversation_messages')
    op.drop_index('idx_msg_agent_type', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_collab_user', table_name='collaboration_operations')
    op.drop_index('idx_collab_time', table_name='collaboration_operations')
    op.drop_index('idx_collab_space', table_name='collaboration_operations')
    op.drop_index('idx_collab_entity', table_name='collaboration_operations')
    op.drop_table('collaboration_operations')
    op.drop_index('idx_pref_user', table_name='user_preferences')
    op.drop_index('idx_pref_type', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('idx_memory_user_type', table_name='user_memories')
    op.drop_index('idx_memory_user', table_name='user_memories')
    op.drop_index('idx_memory_source', table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index('idx_agent_config_user', table_name='user_agent_configs')
    op.drop_table('user_agent_configs')
    op.drop_index(op.f('ix_token_usages_session_id'), table_name='token_usages')
    op.drop_index(op.f('ix_token_usages_request_id'), table_name='token_usages')
    op.drop_index('idx_token_usage_user_created', table_name='token_usages')
    op.drop_index('idx_token_usage_user', table_name='token_usages')
    op.drop_index('idx_token_usage_model', table_name='token_usages')
    op.drop_index('idx_token_usage_feature', table_name='token_usages')
    op.drop_index('idx_token_usage_created', table_name='token_usages')
    op.drop_table('token_usages')
    op.drop_index('idx_acl_user', table_name='resource_acl')
    op.drop_index('idx_acl_resource', table_name='resource_acl')
    op.drop_index('idx_acl_inherit', table_name='resource_acl')
    op.drop_table('resource_acl')
    op.drop_index('idx_summary_round_range', table_name='negotiation_history_summaries')
    op.drop_index('idx_summary_negotiation', table_name='negotiation_history_summaries')
    op.drop_index('idx_summary_layer', table_name='negotiation_history_summaries')
    op.drop_table('negotiation_history_summaries')
    op.drop_index('idx_escrow_log_user', table_name='escrow_transaction_logs')
    op.drop_index('idx_escrow_log_type', table_name='escrow_transaction_logs')
    op.drop_index('idx_escrow_log_escrow', table_name='escrow_transaction_logs')
    op.drop_index('idx_escrow_log_created', table_name='escrow_transaction_logs')
    op.drop_table('escrow_transaction_logs')
    op.drop_index('idx_lineage_source', table_name='data_lineage')
    op.drop_index('idx_lineage_parent', table_name='data_lineage')
    op.drop_index('idx_lineage_current', table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_index('ix_data_assets_type', table_name='data_assets')
    op.drop_index('ix_data_assets_space', table_name='data_assets')
    op.drop_index('ix_data_assets_sensitivity', table_name='data_assets')
    op.drop_index('ix_data_assets_quality', table_name='data_assets')
    op.drop_index('ix_data_assets_owner', table_name='data_assets')
    op.drop_index(op.f('ix_data_assets_asset_id'), table_name='data_assets')
    op.drop_table('data_assets')
    op.drop_index('idx_conv_session_user', table_name='conversation_sessions')
    op.drop_index('idx_conv_session_status', table_name='conversation_sessions')
    op.drop_index('idx_conv_session_space', table_name='conversation_sessions')
    op.drop_index('idx_conv_session_last_msg', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('idx_agent_msg_to', table_name='agent_message_queue')
    op.drop_index('idx_agent_msg_status', table_name='agent_message_queue')
    op.drop_index('idx_agent_msg_priority', table_name='agent_message_queue')
    op.drop_index('idx_agent_msg_negotiation', table_name='agent_message_queue')
    op.drop_index('idx_agent_msg_created', table_name='agent_message_queue')
    op.drop_table('agent_message_queue')
    op.drop_index('idx_outbox_status_created', table_name='outbox_events')
    op.drop_index('idx_outbox_aggregate', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('idx_model_price_provider', table_name='model_prices')
    op.drop_table('model_prices')
    op.drop_index('idx_escrow_status', table_name='escrow_records')
    op.drop_index('idx_escrow_seller', table_name='escrow_records')
    op.drop_index('idx_escrow_negotiation', table_name='escrow_records')
    op.drop_index('idx_escrow_expires', table_name='escrow_records')
    op.drop_index('idx_escrow_buyer', table_name='escrow_records')
    op.drop_table('escrow_records')
    op.drop_index(op.f('ix_blackboard_snapshots_session_id'), table_name='blackboard_snapshots')
    op.drop_index('idx_snapshot_session', table_name='blackboard_snapshots')
    op.drop_table('blackboard_snapshots')
    op.drop_index(op.f('ix_blackboard_events_session_id'), table_name='blackboard_events')
    op.drop_index('idx_blackboard_type', table_name='blackboard_events')
    op.drop_index('idx_blackboard_session_time', table_name='blackboard_events')
    op.drop_index('idx_blackboard_session_seq', table_name='blackboard_events')
    op.drop_index('idx_blackboard_agent', table_name='blackboard_events')
    op.drop_table('blackboard_events')
    op.drop_index(op.f('ix_asset_provenance_asset_id'), table_name='asset_provenance')
    op.drop_index('idx_prov_source', table_name='asset_provenance')
    op.drop_index('idx_prov_asset', table_name='asset_provenance')
    op.drop_table('asset_provenance')
    op.drop_index(op.f('ix_agent_rate_limits_agent_id'), table_name='agent_rate_limits')
    op.drop_index('idx_rate_limit_agent', table_name='agent_rate_limits')
    op.drop_table('agent_rate_limits')
    op.drop_index('idx_intermediate_task', table_name='agent_intermediate_results')
    op.drop_index('idx_intermediate_step', table_name='agent_intermediate_results')
    op.drop_index('idx_intermediate_expires', table_name='agent_intermediate_results')
    op.drop_table('agent_intermediate_results')
    op.drop_index('idx_decision_time', table_name='agent_decision_logs')
    op.drop_index('idx_decision_task', table_name='agent_decision_logs')
    op.drop_index('idx_decision_agent', table_name='agent_decision_logs')
    op.drop_table('agent_decision_logs')
    # ### end Alembic commands ###
